---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elastic-stack-installers
  description: Windows MSI packages for Elastic stack

  annotations:
    backstage.io/source-location: url:https://github.com/elastic/elastic-stack-installers/
    github.com/project-slug: elastic/elastic-stack-installers
    github.com/team-slug: elastic/ingest-fp

  tags:
    - buildkite
    - windows
    - release
    - stack

spec:
  type: tool
  owner: group:ingest-fp
  lifecycle: beta
  dependsOn:
    - resource:github-repository-elastic-stack-installers
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elastic-stack-installers
  description: Buildkite Pipeline for elastic-stack-installers
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elastic-stack-installers

spec:
  type: buildkite-pipeline
  owner: group:ingest-fp
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: Elastic Stack Installer DRA Pipeline
      name: elastic-stack-installers
    spec:
      pipeline_file: ".buildkite/pipeline.yml"
      provider_settings:
        build_branches: true
        build_pull_request_forks: false
        build_pull_requests: true
        publish_commit_status: true
        publish_commit_status_per_step: false
      repository: elastic/elastic-stack-installers
      schedules:
        Daily main:
          branch: main
          cronline: "@daily"
          message: Builds daily `main` stack-installers dra
      teams:
        everyone:
          access_level: BUILD_AND_READ
        ingest-fp: {}
        release-eng: {}
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elastic-stack-installers-trigger
  description: Buildkite Pipeline for elastic-stack-installers triggering
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elastic-stack-installers-trigger
spec:
  type: buildkite-pipeline
  owner: group:ingest-fp
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: Elastic Stack Installer DRA Pipeline Trigger
      name: elastic-stack-installers-trigger
    spec:
      pipeline_file: ".buildkite/scripts/check_beats.sh"
      provider_settings:
        build_branches: false
        build_pull_request_forks: false
        build_pull_requests: false
        publish_commit_status: false
        publish_commit_status_per_step: false
      repository: elastic/elastic-stack-installers
      schedules:
        Daily 8_10:
          branch: "8.10"
          cronline: "*/10 * * * *"
          message: Checking for new beats artefacts for `8.10`
        Weekly main:
          branch: "7.17"
          cronline: "*/10 * * * *"
          message: Checking for new beats artefacts for `7.17`
      teams:
        everyone:
          access_level: BUILD_AND_READ
        ingest-fp: {}
        release-eng: {}
