###
### The following environment variables can be set for testing purposes via the buildkite UI or CLI
###  ONLY_AGENT: "true" - will build only the elastic-agent msi artifact
###

steps:
  - group: ":package: Stack installers Snapshot"
    key: "dra-snapshot"
    steps:
      - label: ":construction_worker: Build stack installers / Snapshot"
        command: ".buildkite/scripts/build.ps1"
        key: "build-snapshot"
        artifact_paths: "c:/users/buildkite/esi/bin/out/**/*.msi"
        agents:
          provider: gcp
          image: family/ci-windows-2022
        env:
          DRA_WORKFLOW: "snapshot"
      - label: ":package: DRA Publish Snapshot"
        if: |
          // Only run when triggered from Unified Release or via PRs. Note that PRs run it in dry-run mode (see dra-publish.sh)
          build.env("BUILDKITE_PULL_REQUEST") != "false" ||
            ( (build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9]+\$/) && build.env("BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG") == "unified-release-snapshot" )
        command: ".buildkite/scripts/dra-publish.sh"
        key: "publish-snapshot"
        depends_on: "build-snapshot"
        agents:
          provider: gcp
        env:
          DRA_WORKFLOW: "snapshot"
  - group: ":package: Stack installers Staging"
    key: "dra-staging"
    steps:
      - label: ":construction_worker: Build stack installers / Staging"
        command: ".buildkite/scripts/build.ps1"
        key: "build-staging"
        artifact_paths: "c:/users/buildkite/esi/bin/out/**/*.msi"
        agents:
          provider: gcp
          image: family/ci-windows-2022
        env:
          DRA_WORKFLOW: "staging"
      - label: ":package: DRA Publish staging"
          // Only run when triggered from Unified Release or via PRs. Note that PRs run it in dry-run mode (see dra-publish.sh)
          build.env("BUILDKITE_PULL_REQUEST") != "false" ||
            ( (build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9]+\$/) && build.env("BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG") == "unified-release-staging" )
        command: ".buildkite/scripts/dra-publish.sh"
        key: "publish-staging"
        depends_on: "build-staging"
        agents:
          provider: gcp
        env:
          DRA_WORKFLOW: "staging"

notify:
  - slack: "#ingest-notifications"
    if: build.branch == 'main'
