env: 
  BRANCH: "7.17"

steps:
  - group: ":beats: Stack installers Snapshot"
    key: "dra-snapshot"
    steps:
    - label: ":hammer: Build stack installers "
      if: build.branch == '7.17' || build.env("RUN_FULL") == "true"
      command: ".buildkite/scripts/build.ps1"
      key: "build"
      artifact_paths: "bin/out/**/*.msi"
      agents:
        provider: gcp
        image: family/ci-windows-2022
    - label: ":package: DRA Publish"
      if: build.branch == '7.17' || build.env("RUN_FULL") == "true"
      command: ".buildkite/scripts/dra-publish.sh"
      key: "publish"
      depends_on: "build"
      agents:
        provider: gcp

notify:
  - slack: "#release-eng-alerts"
    # only notify on main and release branches
    if: build.pull_request.id == 'null'