steps:
  - label: ":hammer: Build stack installers"
    command: ".buildkite/scripts/build.ps1"
    artifact_paths: "bin/out/**/*"
    agents:
      provider: gcp
      image: family/ci-windows-2022
notify:
  - slack: "#release-eng-alerts"
    if: 'build.pull_request.id == null && build.state != "passed"'