env: 
  BRANCH: "7.17"

steps:
  - group: ":beats: Stack installers Snapshot"
    key: "dra-snapshot"
    steps:
    - label: ":hammer: Build stack installers "
      # if: build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9]+\$/ || build.env("RUN_RELEASE") == "true"
      command: ".buildkite/scripts/build.ps1"
      key: "build-snapshot"
      artifact_paths: "bin/out/**/*.msi"
      agents:
        provider: gcp
        image: family/ci-windows-2022
      env: 
        WORKFLOW: "snapshot"
    - label: ":package: DRA Publish Snapshot"
      # if: build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9]+\$/ || build.env("RUN_RELEASE") == "true"
      command: ".buildkite/scripts/dra-publish.sh"
      key: "publish-snapshot"
      depends_on: "build-snapshot"
      agents:
        provider: gcp
      env: 
        WORKFLOW: "snapshot"

notify:
  - slack: "#release-eng-alerts"
    # only notify on main and release branches
    if: build.pull_request.id == 'null'