env: 
# This is set by .buildkite/hooks/pre-command
  BRANCH: "main"
  RUN_AS_MAIN: "FALSE"

steps:
  - group: ":beats: Stack installers Snapshot"
    key: "dra-snapshot"
    steps:
    - label: ":hammer: Build stack installers Snapshot"
      # if: "build.branch == 'main' || build.pull_request.base_branch == 'main' || build.branch =~ /^\\d\\d\\.\\d\\d$/ || build.pull_request.base_branch =~ /^\\d\\d\\.\\d\\d$/ || RUN_AS_MAIN == 'TRUE'"
      command: ".buildkite/scripts/build.ps1"
      key: "build-snapshot"
      artifact_paths: "bin/out/**/*.msi"
      agents:
        provider: gcp
        image: family/ci-windows-2022
      env: 
        WORKFLOW: "snapshot"
    - label: ":package: DRA Publish Snapshot"
      # if: "build.branch == 'main' || build.pull_request.base_branch == 'main' || build.branch =~ /^\\d\\d\\.\\d\\d$/ || build.pull_request.base_branch =~ /^\\d\\d\\.\\d\\d$/ || RUN_AS_MAIN == 'TRUE'"
      command: ".buildkite/scripts/dra-publish.sh"
      key: "publish-snapshot"
      depends_on: "build-snapshot"
      agents:
        provider: gcp
      env: 
        WORKFLOW: "snapshot"
  - group: ":beats: Stack installers Staging :beats:"
    key: "dra-staging"
    steps:
    - label: ":hammer: Build stack installers staging"
      # if: "build.branch =~ /^\\d\\d\\.\\d\\d$/ || build.pull_request.base_branch =~ /^\\d\\d\\.\\d\\d$/ || RUN_AS_MAIN == 'TRUE'"
      command: ".buildkite/scripts/build.ps1"
      key: "build-staging"
      artifact_paths: "bin/out/**/*.msi"
      agents:
        provider: gcp
        image: family/ci-windows-2022
      env: 
        WORKFLOW: "staging"
    - label: ":package: DRA Publish staging"
      # if: "build.branch =~ /^\\d\\d\\.\\d\\d$/ || build.pull_request.base_branch =~ /^\\d\\d\\.\\d\\d$/ || RUN_AS_MAIN == 'TRUE'"
      command: ".buildkite/scripts/dra-publish.sh"
      key: "publish-staging"
      depends_on: "build-staging"
      agents:
        provider: gcp
      env: 
        WORKFLOW: "staging"

notify:
  - slack: "#release-eng-alerts"
    # only notify on main and release branches
    if: "build.branch =~ ^(main|9\\..*|8\\..*|7\\..*)$"