notify:
  - slack:
      channels:
        - "#ingest-notifications"
      message: "<!subteam^S03HZQJLA2D|robots-dx> Version bump to ${NEW_VERSION} — ${BUILDKITE_BUILD_URL}"
    if: (build.branch == 'main' || build.branch =~ /^[0-9]+\.[0-9x]+\$/) && (build.state == 'passed' || build.state == 'failed')
  - slack:
      channels:
        - "#ingest-notifications"
      message: |
        <!subteam^S03HZQJLA2D|robots-dx>
        🚦 Pipeline waiting to be unblocked 🚦
        Repo: `${REPO}`

        New version: `${NEW_VERSION}`
        Branch: `${BRANCH}`
        Workflow: `${WORKFLOW}`
        ${BUILDKITE_BUILD_URL}
    if: build.state == "blocked"

steps:
  - label: "Create branch for version bump"
    if: build.env("WORKFLOW") == "minor"
    command: "make release-major-minor CURRENT_RELEASE=${NEW_VERSION}"
    plugins:
      - elastic/vault-github-token#v0.1.0:
    agents:
      image: "docker.elastic.co/ci-agent-images/observability-robots/ubuntu-build-essential:latest"
